#!/usr/bin/env node
/**
 * Handlr AI — Cross-platform Setup Wizard
 * Run: node setup.js
 *
 * Guides the user through:
 * 1. License key validation
 * 2. OpenAI API key
 * 3. Optional: Anthropic key, email config
 * 4. Creates .env file
 * 5. Installs dependencies
 * 6. Tests connection
 * 7. Sets up auto-start
 */

const readline = require("readline");
const fs = require("fs");
const path = require("path");
const os = require("os");
const { execSync, exec } = require("child_process");

const PLATFORM = os.platform();
const IS_WIN = PLATFORM === "win32";
const IS_MAC = PLATFORM === "darwin";

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((r) => rl.question(q, r));

const BANNER = `
╔═══════════════════════════════════════════╗
║           HANDLR AI — SETUP WIZARD        ║
║     Your AI Butler for Your Computer      ║
╚═══════════════════════════════════════════╝
`;

const ENV_TEMPLATE = `# Handlr AI Configuration
# Generated by setup wizard

# License
LICENSE_KEY={{LICENSE_KEY}}

# Supabase (do not change)
SUPABASE_URL=https://uvdbpxecowapkyouzzcv.supabase.co
SUPABASE_SERVICE_KEY={{SUPABASE_KEY}}

# AI Provider (required)
OPENAI_API_KEY={{OPENAI_KEY}}
MODEL=gpt-4o-mini

# AI Provider (optional — for model switching)
ANTHROPIC_API_KEY={{ANTHROPIC_KEY}}

# Telegram (optional — for Telegram interface)
TELEGRAM_BOT_TOKEN={{TELEGRAM_TOKEN}}
TELEGRAM_OWNER_ID={{TELEGRAM_OWNER}}

# Memory
MEM0_ENABLED=true
`;

async function main() {
  console.clear();
  console.log(BANNER);
  console.log(`Platform: ${IS_WIN ? "Windows" : IS_MAC ? "macOS" : "Linux"}\n`);

  // Step 1: License key
  console.log("── Step 1/5: License Key ──");
  const licenseKey = await ask("Enter your license key: ");
  if (!licenseKey.trim()) {
    console.log("License key is required. Get one at https://handlr.online");
    process.exit(1);
  }

  // Validate license (basic check — real validation happens at runtime)
  console.log("Validating license...");
  try {
    const https = require("https");
    const valid = await new Promise((resolve) => {
      const data = JSON.stringify({ license_key: licenseKey.trim() });
      const req = https.request({
        hostname: "handlr-online.vercel.app",
        path: "/api/license",
        method: "POST",
        headers: { "Content-Type": "application/json", "Content-Length": data.length },
      }, (res) => {
        let body = "";
        res.on("data", (c) => body += c);
        res.on("end", () => {
          try {
            const json = JSON.parse(body);
            resolve(json.valid === true);
          } catch { resolve(true); } // Allow if API unreachable
        });
      });
      req.on("error", () => resolve(true)); // Allow offline setup
      req.write(data);
      req.end();
    });
    if (!valid) {
      console.log("Invalid license key. Please check and try again.");
      process.exit(1);
    }
    console.log("License valid!\n");
  } catch {
    console.log("Could not validate online. Continuing...\n");
  }

  // Step 2: OpenAI API Key
  console.log("── Step 2/5: OpenAI API Key ──");
  console.log("Get one at: https://platform.openai.com/api-keys\n");
  const openaiKey = await ask("Enter your OpenAI API key (sk-...): ");
  if (!openaiKey.trim().startsWith("sk-")) {
    console.log("Warning: Key doesn't start with 'sk-'. Make sure it's correct.\n");
  }

  // Step 3: Optional keys
  console.log("\n── Step 3/5: Optional Configuration ──");
  const anthropicKey = await ask("Anthropic API key (press Enter to skip): ");
  const telegramToken = await ask("Telegram bot token (press Enter to skip): ");
  let telegramOwner = "";
  if (telegramToken.trim()) {
    telegramOwner = await ask("Telegram owner chat ID: ");
  }

  // Step 4: Create .env
  console.log("\n── Step 4/5: Creating Configuration ──");
  let envContent = ENV_TEMPLATE
    .replace("{{LICENSE_KEY}}", licenseKey.trim())
    .replace("{{SUPABASE_KEY}}", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2ZGJweGVjb3dhcGt5b3V6emN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NzYwMjAsImV4cCI6MjA4OTQ1MjAyMH0.6_iXbpN3LQgFVF0xJUnjsYgw99ThZGevkm2b59YqE9M")
    .replace("{{OPENAI_KEY}}", openaiKey.trim())
    .replace("{{ANTHROPIC_KEY}}", anthropicKey.trim())
    .replace("{{TELEGRAM_TOKEN}}", telegramToken.trim())
    .replace("{{TELEGRAM_OWNER}}", telegramOwner.trim());

  fs.writeFileSync(path.join(__dirname, ".env"), envContent);
  console.log(".env file created.\n");

  // Step 5: Install dependencies
  console.log("── Step 5/5: Installing Dependencies ──");
  console.log("This may take a minute...\n");

  try {
    execSync("npm install --production", {
      cwd: __dirname,
      stdio: "inherit",
    });
    console.log("\nDependencies installed!\n");
  } catch (err) {
    console.error("Failed to install dependencies:", err.message);
    console.log("Try running 'npm install' manually.\n");
  }

  // Create data directories
  const dataDir = path.join(__dirname, "data");
  for (const dir of ["chat_history", "screenshots", "documents", "downloads", "tasks", "backups", "browser_profile"]) {
    fs.mkdirSync(path.join(dataDir, dir), { recursive: true });
  }

  // Setup auto-start
  console.log("── Setting up auto-start ──\n");
  await setupAutoStart();

  // Done
  console.log("\n╔═══════════════════════════════════════════╗");
  console.log("║         HANDLR AI — SETUP COMPLETE!       ║");
  console.log("╚═══════════════════════════════════════════╝\n");
  console.log("To start Handlr manually: node index.js");
  console.log("To check status:          pm2 status");
  console.log("To view logs:             pm2 logs handlr\n");
  console.log("Chat interface: https://handlr.online/chat");
  console.log("───────────────────────────────────────────\n");

  rl.close();
}

async function setupAutoStart() {
  // Check if PM2 is available
  try {
    execSync("pm2 --version", { stdio: "pipe" });
  } catch {
    console.log("Installing PM2 (process manager)...");
    try {
      execSync(IS_WIN ? "npm install -g pm2" : "sudo npm install -g pm2", { stdio: "inherit" });
    } catch {
      console.log("Could not install PM2. You can start manually with 'node index.js'");
      return;
    }
  }

  // Start with PM2
  try {
    execSync("pm2 delete handlr 2>/dev/null || true", { cwd: __dirname, stdio: "pipe" });
  } catch {}

  try {
    execSync("pm2 start index.js --name handlr --restart-delay=10000", {
      cwd: __dirname,
      stdio: "inherit",
    });
    execSync("pm2 save", { stdio: "pipe" });

    // Setup startup on boot
    if (IS_WIN) {
      console.log("\nTo auto-start on Windows boot, run:");
      console.log("  pm2 startup");
      console.log("  pm2 save\n");
    } else {
      try {
        const cmd = execSync("pm2 startup", { encoding: "utf8" });
        const sudoCmd = cmd.match(/sudo .+/)?.[0];
        if (sudoCmd) {
          console.log("\nRun this command to enable auto-start on boot:");
          console.log(`  ${sudoCmd}`);
          console.log("  pm2 save\n");
        }
      } catch {}
    }

    console.log("Handlr is now running!");
  } catch (err) {
    console.log("Could not start with PM2:", err.message);
    console.log("Start manually: node index.js");
  }
}

main().catch((err) => {
  console.error("Setup failed:", err.message);
  rl.close();
  process.exit(1);
});
